version: '3.3'

services:
#  composit:
#    build: composit
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#  network:
#    build: network
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#  process:
#    build: process
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - 5433:5432