version: '2.1'

services:
  composit:
    build: composit
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  network:
    build: network
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  process:
    build: process
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  postgres:
    image: 'postgres:15-alpine'
    ports:
      - '5432'
    environment:
      POSTGRES_DB: postgres