
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver

